[versions]

kotlin = "2.3.10"
androidx-test = "1.5.0"
# We compile against an older version of Compose intentionally to support consumers that aren't on
# the latest.
#noinspection GradleDependency
compose = "1.10.1"
# Allows using a different version of Compose to validate that we degrade gracefully on apps
# built with unsupported Compose versions.
#noinspection GradleDependency
compose-old = "1.3.0"
# Use a separate property for the sample so we can test with different versions easily.
compose-sample = "1.6.8"

[libraries]

build-android = "com.android.tools.build:gradle:8.13.2"
build-mavenPublish = "com.vanniktech:gradle-maven-publish-plugin:0.36.0"
build-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
build-compose-compiler = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
build-ktlint = "org.jlleitschuh.gradle:ktlint-gradle:11.6.1"
build-binaryCompatibility = "org.jetbrains.kotlinx:binary-compatibility-validator:0.16.3"
build-dokka = "org.jetbrains.dokka:dokka-gradle-plugin:2.1.0"

appCompat = "androidx.appcompat:appcompat:1.3.1"
constraintLayout = "androidx.constraintlayout:constraintlayout:2.1.0"
curtains = "com.squareup.curtains:curtains:1.2.2"

compose-activity = "androidx.activity:activity-compose:1.3.1"
#noinspection SimilarGradleDependency
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
#noinspection SimilarGradleDependency
compose-testing = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
#noinspection SimilarGradleDependency
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-toolingData = { module = "androidx.compose.ui:ui-tooling-data", version.ref = "compose" }

#noinspection SimilarGradleDependency
compose-sample-activity = "androidx.activity:activity-compose:1.3.1"
#noinspection SimilarGradleDependency
compose-sample-material = { module = "androidx.compose.material:material", version.ref = "compose-sample" }
#noinspection SimilarGradleDependency
compose-sample-testing = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose-sample" }
#noinspection SimilarGradleDependency
compose-sample-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-sample" }

#noinspection SimilarGradleDependency
compose-old-activity = "androidx.activity:activity-compose:1.3.0-alpha02"
#noinspection SimilarGradleDependency
compose-old-material = { module = "androidx.compose.material:material", version.ref = "compose-old" }

test-junit = "junit:junit:4.13"
test-mockito = "org.mockito:mockito-core:3.11.2"
test-robolectric = "org.robolectric:robolectric:4.10.3"
test-truth = "com.google.truth:truth:1.1.3"
test-androidx-core = { module = "androidx.test:core", version.ref = "androidx-test" }
test-androidx-espresso = "androidx.test.espresso:espresso-core:3.5.1"
test-androidx-junit = "androidx.test.ext:junit:1.1.5"
test-androidx-orchestrator = "androidx.test:orchestrator:1.4.2"
test-androidx-rules = { module = "androidx.test:rules", version.ref = "androidx-test" }
test-androidx-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }
